//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetCoreIdentity.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Controllers_Account_AccountController {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Controllers_Account_AccountController() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetCoreIdentity.Resources.Controllers.Account.AccountController", typeof(Controllers_Account_AccountController).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердить.
        /// </summary>
        internal static string AccessButtonAcceptable {
            get {
                return ResourceManager.GetString("AccessButtonAcceptable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предоставить системе тестирования следующие данные.
        /// </summary>
        internal static string AccessData {
            get {
                return ResourceManager.GetString("AccessData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступ к приложеням.
        /// </summary>
        internal static string AccessDataToApplications {
            get {
                return ResourceManager.GetString("AccessDataToApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Система тестирования.
        /// </summary>
        internal static string AccessExaminationsSystem {
            get {
                return ResourceManager.GetString("AccessExaminationsSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        internal static string ButtonsEnter {
            get {
                return ResourceManager.GetString("ButtonsEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин или пароль не верны.
        /// </summary>
        internal static string CommonCredentinalsNotValid {
            get {
                return ResourceManager.GetString("CommonCredentinalsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        internal static string CommonEnter {
            get {
                return ResourceManager.GetString("CommonEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ИИН.
        /// </summary>
        internal static string CommonINN {
            get {
                return ResourceManager.GetString("CommonINN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык интерфейса.
        /// </summary>
        internal static string CommonInterfaceLanguage {
            get {
                return ResourceManager.GetString("CommonInterfaceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        internal static string CommonPassword {
            get {
                return ResourceManager.GetString("CommonPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запомнить меня.
        /// </summary>
        internal static string CommonRememberMe {
            get {
                return ResourceManager.GetString("CommonRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход в систему проверки знаний&lt;br/&gt;
        ///Пожалуйста введите свои учетные данные (иин и пароль),&lt;br/&gt;
        ///что бы получить доступ к системе тестирования.
        /// </summary>
        internal static string CommonWelcomeText {
            get {
                return ResourceManager.GetString("CommonWelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверные логин или пароль.
        /// </summary>
        internal static string CommonWrongCreds {
            get {
                return ResourceManager.GetString("CommonWrongCreds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выход.
        /// </summary>
        internal static string LoggedOut {
            get {
                return ResourceManager.GetString("LoggedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для завершения выхода из системы, пожалуйста, перейдите по ссылке.
        /// </summary>
        internal static string LoggedOutAction {
            get {
                return ResourceManager.GetString("LoggedOutAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to вытйти из системы.
        /// </summary>
        internal static string LoggedOutFinish {
            get {
                return ResourceManager.GetString("LoggedOutFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы находитесь на странице выхода их системы.
        /// </summary>
        internal static string LoggedOutText {
            get {
                return ResourceManager.GetString("LoggedOutText", resourceCulture);
            }
        }
    }
}
